### ISSUE TITLE
Erro banco Itaú Odoo 12

### ISSUE THREAD

**Issue by abrunos** [eduardocereto/pyboleto#73]
erro ao emitir boleto Itaú.

Erro:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo12/odoo12-server/addons/web/controllers/main.py", line 1670, in report_download
    response = self.report_routes(reportname, docids=docids, converter=converter)
  File "/opt/odoo12/odoo12-server/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo12/odoo12-server/addons/web/controllers/main.py", line 1611, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "/opt/odoo12/custom/addons/br_nfe/reports/danfe_report.py", line 33, in render_qweb_pdf
    res_ids, data=data)
  File "/opt/odoo12/custom/addons/br_boleto/reports/boleto.py", line 21, in render_qweb_pdf
    res_ids, data=data)
  File "/opt/odoo12/custom/addons/br_boleto/reports/report.py", line 45, in render_qweb_pdf
    pdf_string = Boleto.get_pdfs(boleto_list)
  File "/opt/odoo12/custom/addons/br_boleto/boleto/document.py", line 145, in get_pdfs
    boleto.drawBoleto(boleto_list[i])
  File "/usr/local/lib/python3.5/dist-packages/pyboleto-0.3.1-py3.5.egg/pyboleto/pdf.py", line 815, in drawBoleto
    d = self._drawReciboCaixa(boleto_dados, x, y)
  File "/usr/local/lib/python3.5/dist-packages/pyboleto-0.3.1-py3.5.egg/pyboleto/pdf.py", line 672, in _drawReciboCaixa
    boleto_dados.format_nosso_numero()
  File "/usr/local/lib/python3.5/dist-packages/pyboleto-0.3.1-py3.5.egg/pyboleto/bank/itau.py", line 46, in format_nosso_numero
    self.dv_nosso_numero)
  File "/usr/local/lib/python3.5/dist-packages/pyboleto-0.3.1-py3.5.egg/pyboleto/bank/itau.py", line 32, in dv_nosso_numero
    return self.modulo10(composto)
  File "/usr/local/lib/python3.5/dist-packages/pyboleto-0.3.1-py3.5.egg/pyboleto/data.py", line 459, in modulo10
    parcial = int(c) * peso
ValueError: invalid literal for int() with base 10: 'G'

**Comment by abrunos** [comment]
Erro:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo12/odoo12-server/addons/web/controllers/main.py", line 1670, in report_download
    response = self.report_routes(reportname, docids=docids, converter=converter)
  File "/opt/odoo12/odoo12-server/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo12/odoo12-server/addons/web/controllers/main.py", line 1611, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "/opt/odoo12/custom/addons/br_nfe/reports/danfe_report.py", line 33, in render_qweb_pdf
    res_ids, data=data)
  File "/opt/odoo12/custom/addons/br_boleto/reports/boleto.py", line 21, in render_qweb_pdf
    res_ids, data=data)
  File "/opt/odoo12/custom/addons/br_boleto/reports/report.py", line 45, in render_qweb_pdf
    pdf_string = Boleto.get_pdfs(boleto_list)
  File "/opt/odoo12/custom/addons/br_boleto/boleto/document.py", line 145, in get_pdfs
    boleto.drawBoleto(boleto_list[i])
  File "/usr/local/lib/python3.5/dist-packages/pyboleto-0.3.1-py3.5.egg/pyboleto/pdf.py", line 815, in drawBoleto
    d = self._drawReciboCaixa(boleto_dados, x, y)
  File "/usr/local/lib/python3.5/dist-packages/pyboleto-0.3.1-py3.5.egg/pyboleto/pdf.py", line 672, in _drawReciboCaixa
    boleto_dados.format_nosso_numero()
  File "/usr/local/lib/python3.5/dist-packages/pyboleto-0.3.1-py3.5.egg/pyboleto/bank/itau.py", line 46, in format_nosso_numero
    self.dv_nosso_numero)
  File "/usr/local/lib/python3.5/dist-packages/pyboleto-0.3.1-py3.5.egg/pyboleto/bank/itau.py", line 32, in dv_nosso_numero
    return self.modulo10(composto)
  File "/usr/local/lib/python3.5/dist-packages/pyboleto-0.3.1-py3.5.egg/pyboleto/data.py", line 459, in modulo10
    parcial = int(c) * peso
ValueError: invalid literal for int() with base 10: 'G'
